version: '3.1'
services:
  db:
    image: 'postgres'
    container_name: 'bsmple_inventory'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
